import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name='description' content='Generated by create-t3-app' />
            </Head>
            <main>
                <div>
                    <div>
                        <Link href='https://create.t3.gg/en/usage/first-steps' target='_blank'>
                            <h3>First Steps →</h3>
                            <div>
                                Just the basics - Everything you need to know to set up your
                                database and authentication.
                            </div>
                        </Link>
                        <Link href='https://create.t3.gg/en/introduction' target='_blank'>
                            <h3>Documentation →</h3>
                            <div>
                                Learn more about Create T3 App, the libraries it uses, and how to
                                deploy it.
                            </div>
                        </Link>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Home
